export enum FarmStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum FarmType {
  NORMAL = "NORMAL",
  BANK_DEPOSIT_PROOF = "BANK_DEPOSIT_PROOF",
}

export enum ProofType {
  INVENTORY_PROOF = "INVENTORY_PROOF",
  BANK_PROOF = "BANK_PROOF",
}

export enum GoalType {
  GLOBAL_MAIN = "GLOBAL_MAIN",
  GLOBAL_WEEKLY = "GLOBAL_WEEKLY",
  GLOBAL_MONTHLY = "GLOBAL_MONTHLY",
  INDIVIDUAL_WEEKLY = "INDIVIDUAL_WEEKLY",
  INDIVIDUAL_MONTHLY = "INDIVIDUAL_MONTHLY",
}

export enum InventoryMovementType {
  IN = "IN",
  OUT = "OUT",
  ADJUSTMENT = "ADJUSTMENT",
}

export enum VehicleStatus {
  STORED = "STORED",
  OUT = "OUT",
  DETAINED = "DETAINED",
}

export enum VehicleHistoryAction {
  TAKEN = "TAKEN",
  STORED = "STORED",
  DETAINED = "DETAINED",
  RELEASED = "RELEASED",
}

export enum AuditAction {
  USER_LOGIN = "USER_LOGIN",
  USER_UPDATED = "USER_UPDATED",
  FARM_CREATED = "FARM_CREATED",
  FARM_APPROVED = "FARM_APPROVED",
  FARM_REJECTED = "FARM_REJECTED",
  GOAL_CREATED = "GOAL_CREATED",
  GOAL_UPDATED = "GOAL_UPDATED",
  GOAL_DELETED = "GOAL_DELETED",
  GOAL_ACTIVATED = "GOAL_ACTIVATED",
  GOAL_DEACTIVATED = "GOAL_DEACTIVATED",
  INVENTORY_ITEM_CREATED = "INVENTORY_ITEM_CREATED",
  INVENTORY_MOVEMENT_CREATED = "INVENTORY_MOVEMENT_CREATED",
  VEHICLE_CREATED = "VEHICLE_CREATED",
  VEHICLE_UPDATED = "VEHICLE_UPDATED",
  VEHICLE_DELETED = "VEHICLE_DELETED",
  VEHICLE_TAKEN = "VEHICLE_TAKEN",
  VEHICLE_STORED = "VEHICLE_STORED",
  VEHICLE_DETAINED = "VEHICLE_DETAINED",
  VEHICLE_RELEASED = "VEHICLE_RELEASED",
  ROLE_ASSIGNED = "ROLE_ASSIGNED",
  ROLE_REMOVED = "ROLE_REMOVED",
  NOTIFICATION_SENT = "NOTIFICATION_SENT",
  UPLOAD_CREATED = "UPLOAD_CREATED",
  UPLOAD_DELETED = "UPLOAD_DELETED",
  CONFIG_UPDATED = "CONFIG_UPDATED",
  MEMBER_SYNCED = "MEMBER_SYNCED",
  MEMBER_NAME_CHANGED = "MEMBER_NAME_CHANGED",
  MEMBER_ROLE_CHANGED = "MEMBER_ROLE_CHANGED",
  MEMBER_ACCESS_GRANTED = "MEMBER_ACCESS_GRANTED",
  MEMBER_ACCESS_REVOKED = "MEMBER_ACCESS_REVOKED",
  DISCORD_ROLE_CONFIG_UPDATED = "DISCORD_ROLE_CONFIG_UPDATED",
}

export enum Permission {
  VIEW_DASHBOARD = "VIEW_DASHBOARD",
  CREATE_FARM = "CREATE_FARM",
  VIEW_OWN_FARMS = "VIEW_OWN_FARMS",
  VIEW_ALL_FARMS = "VIEW_ALL_FARMS",
  REVIEW_FARM = "REVIEW_FARM",
  VIEW_RANKING = "VIEW_RANKING",
  VIEW_GOAL = "VIEW_GOAL",
  VIEW_GOALS = "VIEW_GOALS",
  MANAGE_GOAL = "MANAGE_GOAL",
  MANAGE_GOALS = "MANAGE_GOALS",
  VIEW_MEMBERS = "VIEW_MEMBERS",
  MANAGE_MEMBERS = "MANAGE_MEMBERS",
  MANAGE_ROLES = "MANAGE_ROLES",
  VIEW_INVENTORY = "VIEW_INVENTORY",
  MANAGE_INVENTORY = "MANAGE_INVENTORY",
  VIEW_GARAGE = "VIEW_GARAGE",
  MANAGE_GARAGE = "MANAGE_GARAGE",
  TAKE_VEHICLE = "TAKE_VEHICLE",
  STORE_VEHICLE = "STORE_VEHICLE",
  VIEW_VEHICLE_HISTORY = "VIEW_VEHICLE_HISTORY",
  VIEW_LOGS = "VIEW_LOGS",
  VIEW_DISCORD = "VIEW_DISCORD",
  MANAGE_CONFIG = "MANAGE_CONFIG",
  MANAGE_MEMBER_ACCESS = "MANAGE_MEMBER_ACCESS",
  MANAGE_MEMBER_ROLE = "MANAGE_MEMBER_ROLE",
  MANAGE_DISCORD_ROLE_CONFIG = "MANAGE_DISCORD_ROLE_CONFIG",
  SYNC_DISCORD_MEMBERS = "SYNC_DISCORD_MEMBERS",
}

export enum DiscordRoleTier {
  MEMBER = "MEMBER",
  SUPERVISOR = "SUPERVISOR",
  MANAGER = "MANAGER",
  OWNER = "OWNER",
}

export enum SiteAccessStatus {
  ACTIVE = "ACTIVE",
  BLOCKED = "BLOCKED",
}

export enum OrganizationRank {
  LEADER = "LEADER",
  SUB_LEADER = "SUB_LEADER",
  LEVEL_1 = "LEVEL_1",
  LEVEL_2 = "LEVEL_2",
  LEVEL_3 = "LEVEL_3",
  AFK = "AFK",
}
